### ISSUE TITLE
好像还差个退出系统的函数exit_sys

### ISSUE THREAD

**Issue by LitStronger** [WingLim/oslab#2]
![image](https://user-images.githubusercontent.com/44419860/85218464-27770300-b3cd-11ea-91e7-551dc2691b7c.png)

**Comment by WingLim** [comment]
在这里，已经实现
https://github.com/WingLim/oslab/blob/443fd9b815e7c6167629d73553f6f4884c7b102d/lab5/simplefs.c#L42
